"""
Universal Agricultural Machine Learning Schema (UAMS) v2.0

Updated to cover all 172 Data ADES source files plus root-level master datasets.
Columns O-Z are new groups added for full Data ADES coverage.
"""

UAMS_VERSION = "2.0"

UAMS_COLUMNS = [
    # A. Paper Metadata
    "Paper_ID",
    "DOI",
    "Journal",
    "Year",
    "Authors",
    "Country",
    "Title",
    "Institution",
    # B. Crop Information
    "Crop",
    "Scientific_Name",
    "Variety",
    "Season",
    "Growth_Duration_Days",
    "Growth_Stage",
    "Cover_Crop",
    "Previous_Crop",
    "Intercrop_Name",
    # C. Experimental Design
    "Design",
    "Replications",
    "Plot_Size",
    "Spacing_Row",
    "Spacing_Plant",
    "Sample_Size",
    "Location",
    "State",
    "Site",
    "Plot_ID",
    "Block",
    "Experiment_Objective",
    "Sowing_Date",
    "Harvest_Date",
    # D. Environment
    "Latitude",
    "Longitude",
    "Altitude",
    "Temperature_Max",
    "Temperature_Min",
    "Average_Temperature",
    "Rainfall",
    "Humidity",
    "Solar_Radiation",
    "Wind_Speed",
    "ET0",
    "Climate_Zone",
    # E. Soil Properties
    "Soil_pH",
    "EC",
    "Organic_Carbon",
    "Organic_Matter",
    "Nitrogen",
    "Phosphorus",
    "Potassium",
    "Sulphur",
    "Iron",
    "Copper",
    "Manganese",
    "Zinc",
    "Calcium",
    "Magnesium",
    "Boron",
    "Molybdenum",
    "Sodium",
    "Chlorine",
    "CEC",
    "Soil_Bulk_Density",
    "Soil_Clay_Pct",
    "Soil_Silt_Pct",
    "Soil_Sand_Pct",
    "Soil_Texture",
    "Soil_Class",
    "Soil_Depth_cm",
    # F. Fertilizer Information
    "Treatment",
    "Fertilizer_Name",
    "Organic_Fertilizer",
    "Biofertilizer",
    "Dose",
    "Application_Method",
    "Application_Interval",
    "Fertilizer_Calcium",
    "Fertilizer_Magnesium",
    "Fertilizer_Boron",
    "Fertilizer_Chlorine",
    "Fertilizer_Molybdenum",
    # G. Crop Growth Parameters
    "Shoot_Length_cm",
    "Root_Length_cm",
    "Plant_Height_cm",
    "Shoot_Biomass_g",
    "Root_Biomass_g",
    "Leaf_Area_cm2",
    "Leaf_Number",
    "Tillers",
    "Root_Diameter_mm",
    "SPAD",
    "Moisture_Content",
    "Dry_Matter",
    "Stem_Diameter_mm",
    "Branches",
    "Nodes",
    "Flowers",
    "Plant_Height_30_cm",
    "Plant_Height_60_cm",
    "Plant_Height_90_cm",
    "Plant_Height_120_cm",
    "Leaf_Area_30_cm2",
    "Leaf_Area_60_cm2",
    "Leaf_Area_90_cm2",
    "Leaf_Area_120_cm2",
    "Branches_60",
    "Branches_90",
    "Flowers_60",
    # H. Yield Parameters
    "Yield_per_Plot",
    "Yield_per_Acre",
    "Yield_per_Hectare",
    "Fruit_Number",
    "Fruit_Weight",
    "Fruit_Diameter_mm",
    "Spike_Length",
    "Seeds_per_Spike",
    "100_Seed_Weight",
    "Root_Weight",
    "Pod_Weight",
    "Harvest_Index",
    "Biomass_Yield",
    "FruitWeight_90_g",
    "FruitWeight_120_g",
    "FruitDiameter_90_mm",
    "FruitDiameter_120_mm",
    "YieldPlot_90_g",
    "YieldPlot_120_g",
    "Yield_13pct_Moisture",
    "Marketable_Yield",
    "Biological_Yield",
    "Stover_Yield",
    "Seed_Yield",
    "Pods_Number",
    "Seeds_per_Pod",
    "Weed_Biomass",
    # I. Grain Quality
    "Protein",
    "Ash",
    "Gluten",
    "Fiber",
    "Carbohydrates",
    "Fat",
    "Nitrogen_Content",
    "Phosphorus_Content",
    "Potassium_Content",
    "Iron_Content",
    "Copper_Content",
    "Zinc_Content",
    "Manganese_Content",
    "Sulphur_Content",
    "Calcium_Content",
    "Magnesium_Content",
    "Boron_Content",
    "Chlorine_Content",
    "Molybdenum_Content",
    "Starch",
    "Oil",
    # J. ML Target Variables
    "Target_Yield",
    "Target_Fertilizer",
    "Target_Nitrogen",
    "Target_Phosphorus",
    "Target_Potassium",
    # K. Engineered Features (Agent 06)
    "Growing_Degree_Days",
    "Heat_Units",
    "Harvest_Index_Calc",
    "Nitrogen_Use_Efficiency",
    "Water_Use_Efficiency",
    "Rainfall_Anomaly",
    "Stress_Index",
    "Disease_Risk_Index",
    "Yield_per_Plant",
    "Yield_per_Plot_Calc",
    "Yield_per_Hectare_Calc",
    "Temp_x_Rainfall",
    "N_x_P",
    "Temp_squared",
    "Rainfall_7d_MA",
    "Temp_7d_MA",
    # L. Leakage Labels (Agent 07)
    "Feature_Available_Before_Prediction",
    # M. Encoded Variables (Agent 08)
    "Crop_Code",
    "Season_Code",
    "Variety_Code",
    "Fertilizer_Code",
    "Soil_Texture_Code",
    "Country_Code",
    # N. ML Predictions
    "Predicted_Yield",
    "Expected_Biomass",
    "Expected_Plant_Height",
    "Recommended_Fertilizer",
    "Recommended_Dose",
    "Recommended_Application_Interval",
    "Expected_Yield_Increase",
    "Confidence_Score",
    "Recommendation_Summary",
    # O. Soil Biological Properties (Data ADES)
    "SOC_Mineralization",
    "Residue_C_Decomposition",
    "Potential_Evapotranspiration",
    "Soil_Moisture",
    "Soil_Nitrate_N",
    "Soil_Ammonium_N",
    "Soil_Available_K",
    "Soil_POC",
    "Soil_DOC",
    "Soil_LOC",
    "Soil_MBC",
    "Soil_MBN",
    "Soil_Carbon_Walkley_Black",
    "Soil_Nitrogen_Kjeldahl",
    "Soil_Nitrogen_Alkaline_Permanganate",
    "Soil_Sulphur_Available",
    "Soil_Sulphur_Mehlich3",
    "Soil_NO3",
    "Soil_NH4",
    "Soil_N_Parco2020",
    "Soil_N_DeSilva2008",
    "Soil_Ca_Ammonium_Acetate",
    "Soil_Mg_Ammonium_Acetate",
    "Soil_K_Ammonium_Acetate",
    # P. Soil Enzyme Activity (Data ADES)
    "Soil_Glucosidase",
    "Soil_Xylosidase",
    "Soil_Cellobiosidase",
    "Beta_Glucosidase",
    "Peroxidase",
    "Polyphenol_Oxidase",
    "N_Acetyl_Glucosaminidase",
    "Leucine_Aminopeptidase",
    "Phosphatase",
    "Catalase",
    "Urease",
    "Dehydrogenase",
    # Q. Soil Microbial Community (Data ADES)
    "Bacterial_Diversity_Chao1",
    "Bacterial_Diversity_Shannon",
    "Fungal_Diversity_Chao1",
    "Fungal_Diversity_Shannon",
    "Total_PLFAs",
    "Gram_Positive_PLFAs",
    "Gram_Negative_PLFAs",
    "Fungal_PLFAs",
    "Bacterial_PLFAs",
    "Actinomycetes_PLFAs",
    # R. Remote Sensing Indices (Data ADES)
    "NDVI",
    "EVI",
    "SAVI",
    "NDWI",
    "NDRE",
    "Canopy_Temperature",
    "CIG",
    "CIRE",
    # S. Soil Exchangeable Cations & Saturation (Data ADES)
    "Calcium_Mehlich3",
    "Calcium_Saturation",
    "Magnesium_Saturation",
    "Sodium_Saturation",
    "Potassium_Saturation",
    "Hydrogen_Saturation",
    # T. Water Extractable Organic (Data ADES)
    "Water_Extractable_Nitrate",
    "Water_Extractable_Organic_Carbon",
    "Water_Extractable_Organic_Nitrogen",
    "Water_Extractable_NH4",
    "Water_Extractable_CN_Ratio",
    # U. Soil Physical Properties (Data ADES)
    "Aggregate_Stability",
    "Soil_Respiration",
    "Infiltration_Rate",
    # V. Nematode Ecology (Data ADES)
    "Nematode_Maturity_Index",
    "Nematode_Plant_Parasitic_Index",
    "Nematode_Channel_Index",
    "Nematode_Basal_Index",
    "Nematode_Enrichment_Index",
    "Nematode_Structure_Index",
    "Nematode_Total_Biomass_mg",
    # W. Economic Parameters (Data ADES)
    "Total_Cost",
    "Total_Return",
    "Net_Profit",
    "Benefit_Cost_Ratio",
    "System_Benefit_USD_ha",
    "Off_Season_Contribution_Pct",
    "System_Water_Use_Efficiency",
    # X. Nutrient Uptake (Data ADES)
    "Phosphorus_Uptake",
    "Nitrogen_Uptake",
    "Potassium_Uptake",
    "Sulphur_Uptake",
    "Calcium_Uptake",
    "Magnesium_Uptake",
    "Boron_Uptake",
    "Chlorine_Uptake",
    "Copper_Uptake",
    "Iron_Uptake",
    "Manganese_Uptake",
    "Molybdenum_Uptake",
    "Zinc_Uptake",
    # Y. Irrigation & Management (Data ADES)
    "Irrigation_Method",
    "Irrigation_mm",
    "Sowing_Density",
    "Harvest_Density",
    "Cultivation_Method",
    "N_Fixation",
    # Z. Soil pH Variants & Measurement Methods (Data ADES)
    "Soil_pH_CaCl2",
    "Soil_pH_KCl",
]

SCHEMA_GROUPS = {
    "A. Paper Metadata": [
        "Paper_ID",
        "DOI",
        "Journal",
        "Year",
        "Authors",
        "Country",
        "Title",
        "Institution",
    ],
    "B. Crop Information": [
        "Crop",
        "Scientific_Name",
        "Variety",
        "Season",
        "Growth_Duration_Days",
        "Growth_Stage",
        "Cover_Crop",
        "Previous_Crop",
        "Intercrop_Name",
    ],
    "C. Experimental Design": [
        "Design",
        "Replications",
        "Plot_Size",
        "Spacing_Row",
        "Spacing_Plant",
        "Sample_Size",
        "Location",
        "State",
        "Site",
        "Plot_ID",
        "Block",
        "Experiment_Objective",
        "Sowing_Date",
        "Harvest_Date",
    ],
    "D. Environment": [
        "Latitude",
        "Longitude",
        "Altitude",
        "Temperature_Max",
        "Temperature_Min",
        "Average_Temperature",
        "Rainfall",
        "Humidity",
        "Solar_Radiation",
        "Wind_Speed",
        "ET0",
        "Climate_Zone",
    ],
    "E. Soil Properties": [
        "Soil_pH",
        "EC",
        "Organic_Carbon",
        "Organic_Matter",
        "Nitrogen",
        "Phosphorus",
        "Potassium",
        "Sulphur",
        "Iron",
        "Copper",
        "Manganese",
        "Zinc",
        "Calcium",
        "Magnesium",
        "Boron",
        "Molybdenum",
        "Sodium",
        "Chlorine",
        "CEC",
        "Soil_Bulk_Density",
        "Soil_Clay_Pct",
        "Soil_Silt_Pct",
        "Soil_Sand_Pct",
        "Soil_Texture",
        "Soil_Class",
        "Soil_Depth_cm",
    ],
    "F. Fertilizer Information": [
        "Treatment",
        "Fertilizer_Name",
        "Organic_Fertilizer",
        "Biofertilizer",
        "Dose",
        "Application_Method",
        "Application_Interval",
        "Fertilizer_Calcium",
        "Fertilizer_Magnesium",
        "Fertilizer_Boron",
        "Fertilizer_Chlorine",
        "Fertilizer_Molybdenum",
    ],
    "G. Crop Growth Parameters": [
        "Shoot_Length_cm",
        "Root_Length_cm",
        "Plant_Height_cm",
        "Shoot_Biomass_g",
        "Root_Biomass_g",
        "Leaf_Area_cm2",
        "Leaf_Number",
        "Tillers",
        "Root_Diameter_mm",
        "SPAD",
        "Moisture_Content",
        "Dry_Matter",
        "Stem_Diameter_mm",
        "Branches",
        "Nodes",
        "Flowers",
        "Plant_Height_30_cm",
        "Plant_Height_60_cm",
        "Plant_Height_90_cm",
        "Plant_Height_120_cm",
        "Leaf_Area_30_cm2",
        "Leaf_Area_60_cm2",
        "Leaf_Area_90_cm2",
        "Leaf_Area_120_cm2",
        "Branches_60",
        "Branches_90",
        "Flowers_60",
    ],
    "H. Yield Parameters": [
        "Yield_per_Plot",
        "Yield_per_Acre",
        "Yield_per_Hectare",
        "Fruit_Number",
        "Fruit_Weight",
        "Fruit_Diameter_mm",
        "Spike_Length",
        "Seeds_per_Spike",
        "100_Seed_Weight",
        "Root_Weight",
        "Pod_Weight",
        "Harvest_Index",
        "Biomass_Yield",
        "FruitWeight_90_g",
        "FruitWeight_120_g",
        "FruitDiameter_90_mm",
        "FruitDiameter_120_mm",
        "YieldPlot_90_g",
        "YieldPlot_120_g",
        "Yield_13pct_Moisture",
        "Marketable_Yield",
        "Biological_Yield",
        "Stover_Yield",
        "Seed_Yield",
        "Pods_Number",
        "Seeds_per_Pod",
        "Weed_Biomass",
    ],
    "I. Grain Quality": [
        "Protein",
        "Ash",
        "Gluten",
        "Fiber",
        "Carbohydrates",
        "Fat",
        "Nitrogen_Content",
        "Phosphorus_Content",
        "Potassium_Content",
        "Iron_Content",
        "Copper_Content",
        "Zinc_Content",
        "Manganese_Content",
        "Sulphur_Content",
        "Calcium_Content",
        "Magnesium_Content",
        "Boron_Content",
        "Chlorine_Content",
        "Molybdenum_Content",
        "Starch",
        "Oil",
    ],
    "J. ML Target Variables": [
        "Target_Yield",
        "Target_Fertilizer",
        "Target_Nitrogen",
        "Target_Phosphorus",
        "Target_Potassium",
    ],
    "K. Engineered Features": [
        "Growing_Degree_Days",
        "Heat_Units",
        "Harvest_Index_Calc",
        "Nitrogen_Use_Efficiency",
        "Water_Use_Efficiency",
        "Rainfall_Anomaly",
        "Stress_Index",
        "Disease_Risk_Index",
        "Yield_per_Plant",
        "Yield_per_Plot_Calc",
        "Yield_per_Hectare_Calc",
        "Temp_x_Rainfall",
        "N_x_P",
        "Temp_squared",
        "Rainfall_7d_MA",
        "Temp_7d_MA",
    ],
    "L. Leakage Labels": ["Feature_Available_Before_Prediction"],
    "M. Encoded Variables": [
        "Crop_Code",
        "Season_Code",
        "Variety_Code",
        "Fertilizer_Code",
        "Soil_Texture_Code",
        "Country_Code",
    ],
    "N. ML Predictions": [
        "Predicted_Yield",
        "Expected_Biomass",
        "Expected_Plant_Height",
        "Recommended_Fertilizer",
        "Recommended_Dose",
        "Recommended_Application_Interval",
        "Expected_Yield_Increase",
        "Confidence_Score",
        "Recommendation_Summary",
    ],
    "O. Soil Biological Properties": [
        "SOC_Mineralization",
        "Residue_C_Decomposition",
        "Potential_Evapotranspiration",
        "Soil_Moisture",
        "Soil_Nitrate_N",
        "Soil_Ammonium_N",
        "Soil_Available_K",
        "Soil_POC",
        "Soil_DOC",
        "Soil_LOC",
        "Soil_MBC",
        "Soil_MBN",
        "Soil_Carbon_Walkley_Black",
        "Soil_Nitrogen_Kjeldahl",
        "Soil_Nitrogen_Alkaline_Permanganate",
        "Soil_Sulphur_Available",
        "Soil_Sulphur_Mehlich3",
        "Soil_NO3",
        "Soil_NH4",
        "Soil_N_Parco2020",
        "Soil_N_DeSilva2008",
        "Soil_Ca_Ammonium_Acetate",
        "Soil_Mg_Ammonium_Acetate",
        "Soil_K_Ammonium_Acetate",
    ],
    "P. Soil Enzyme Activity": [
        "Soil_Glucosidase",
        "Soil_Xylosidase",
        "Soil_Cellobiosidase",
        "Beta_Glucosidase",
        "Peroxidase",
        "Polyphenol_Oxidase",
        "N_Acetyl_Glucosaminidase",
        "Leucine_Aminopeptidase",
        "Phosphatase",
        "Catalase",
        "Urease",
        "Dehydrogenase",
    ],
    "Q. Soil Microbial Community": [
        "Bacterial_Diversity_Chao1",
        "Bacterial_Diversity_Shannon",
        "Fungal_Diversity_Chao1",
        "Fungal_Diversity_Shannon",
        "Total_PLFAs",
        "Gram_Positive_PLFAs",
        "Gram_Negative_PLFAs",
        "Fungal_PLFAs",
        "Bacterial_PLFAs",
        "Actinomycetes_PLFAs",
    ],
    "R. Remote Sensing Indices": [
        "NDVI",
        "EVI",
        "SAVI",
        "NDWI",
        "NDRE",
        "Canopy_Temperature",
        "CIG",
        "CIRE",
    ],
    "S. Soil Exchangeable Cations": [
        "Calcium_Mehlich3",
        "Calcium_Saturation",
        "Magnesium_Saturation",
        "Sodium_Saturation",
        "Potassium_Saturation",
        "Hydrogen_Saturation",
    ],
    "T. Water Extractable Organic": [
        "Water_Extractable_Nitrate",
        "Water_Extractable_Organic_Carbon",
        "Water_Extractable_Organic_Nitrogen",
        "Water_Extractable_NH4",
        "Water_Extractable_CN_Ratio",
    ],
    "U. Soil Physical Properties": ["Aggregate_Stability", "Soil_Respiration", "Infiltration_Rate"],
    "V. Nematode Ecology": [
        "Nematode_Maturity_Index",
        "Nematode_Plant_Parasitic_Index",
        "Nematode_Channel_Index",
        "Nematode_Basal_Index",
        "Nematode_Enrichment_Index",
        "Nematode_Structure_Index",
        "Nematode_Total_Biomass_mg",
    ],
    "W. Economic Parameters": [
        "Total_Cost",
        "Total_Return",
        "Net_Profit",
        "Benefit_Cost_Ratio",
        "System_Benefit_USD_ha",
        "Off_Season_Contribution_Pct",
        "System_Water_Use_Efficiency",
    ],
    "X. Nutrient Uptake": [
        "Phosphorus_Uptake",
        "Nitrogen_Uptake",
        "Potassium_Uptake",
        "Sulphur_Uptake",
        "Calcium_Uptake",
        "Magnesium_Uptake",
        "Boron_Uptake",
        "Chlorine_Uptake",
        "Copper_Uptake",
        "Iron_Uptake",
        "Manganese_Uptake",
        "Molybdenum_Uptake",
        "Zinc_Uptake",
    ],
    "Y. Irrigation & Management": [
        "Irrigation_Method",
        "Irrigation_mm",
        "Sowing_Density",
        "Harvest_Density",
        "Cultivation_Method",
        "N_Fixation",
    ],
    "Z. Soil pH Variants": ["Soil_pH_CaCl2", "Soil_pH_KCl"],
}

VARIANT_MAP = {
    "100_seed_weight": "100_Seed_Weight",
    "acid_phosphatase": "Phosphatase",
    "actinomycetes_plfas": "Actinomycetes_PLFAs",
    "actual_irrigation_mm": "Irrigation_mm",
    "actual_rainfall_during trial_mm": "Rainfall",
    "aggregate_stability": "Aggregate_Stability",
    "agy_lsd_kg_fresh_ha": "Yield_per_Hectare",
    "agy_mean_kg_dm_ha": "Biomass_Yield",
    "agy_mean_kg_fresh_ha": "Yield_per_Hectare",
    "agy_sd_kg_fresh_ha": "Yield_per_Hectare",
    "agy_se_kg_fresh_ha": "Yield_per_Hectare",
    "alkaline_phosphatase": "Phosphatase",
    "altitude": "Altitude",
    "amendment": "Fertilizer_Name",
    "annual_rainfall_mean_mm_year": "Rainfall",
    "ap (mg/kg)": "Phosphorus",
    "application_interval": "Application_Interval",
    "application_method": "Application_Method",
    "ash": "Ash",
    "ash_%": "Ash",
    "ash_pct": "Ash",
    "authors": "Authors",
    "available_k": "Potassium",
    "available_n": "Nitrogen",
    "available_p": "Phosphorus",
    "average_temperature": "Average_Temperature",
    "avg_temp": "Average_Temperature",
    "b": "Boron",
    "b_uptake": "Boron_Uptake",
    "bacterial_chao1": "Bacterial_Diversity_Chao1",
    "bacterial_plfas": "Bacterial_PLFAs",
    "bacterial_shannon": "Bacterial_Diversity_Shannon",
    "basal soc mineralization": "SOC_Mineralization",
    "bc_ratio": "Benefit_Cost_Ratio",
    "beta_glucosidase": "Beta_Glucosidase",
    "bi": "Nematode_Basal_Index",
    "bio_fertilizer": "Biofertilizer",
    "biofertilizer": "Biofertilizer",
    "biological_yield": "Biological_Yield",
    "biomass_yield": "Biomass_Yield",
    "block": "Block",
    "boron": "Boron",
    "boron_content": "Boron_Content",
    "boron_uptake": "Boron_Uptake",
    "branches": "Branches",
    "branches_60": "Branches_60",
    "branches_90": "Branches_90",
    "branches_plant": "Branches",
    "ca": "Calcium",
    "ca_uptake": "Calcium_Uptake",
    "calcium": "Calcium",
    "calcium_content": "Calcium_Content",
    "calcium_mehlich3": "Calcium_Mehlich3",
    "calcium_saturation_%": "Calcium_Saturation",
    "calcium_uptake": "Calcium_Uptake",
    "canopy_temp": "Canopy_Temperature",
    "canopy_temperature": "Canopy_Temperature",
    "carbohydrates": "Carbohydrates",
    "carbs": "Carbohydrates",
    "catalase": "Catalase",
    "cellobiosidase": "Soil_Cellobiosidase",
    "chlorine_content": "Chlorine_Content",
    "chlorine_uptake": "Chlorine_Uptake",
    "chlorophyll": "SPAD",
    "chlorophyll_content": "SPAD",
    "chlorophyll_index_green": "CIG",
    "chlorophyll_index_red_edge": "CIRE",
    "chlorophyll_spad": "SPAD",
    "ci": "Nematode_Channel_Index",
    "cig": "CIG",
    "cire": "CIRE",
    "cl_uptake": "Chlorine_Uptake",
    "climate_zone": "Climate_Zone",
    "coby_mean_kg_fresh_ha": "Yield_per_Hectare",
    "confidence": "Confidence_Score",
    "confidence_score": "Confidence_Score",
    "copper": "Copper",
    "copper_content": "Copper_Content",
    "copper_ppm": "Copper",
    "copper_uptake": "Copper_Uptake",
    "country": "Country",
    "cover crop": "Cover_Crop",
    "cover_crop": "Cover_Crop",
    "cpcon_fe_mean_kg_kg_dm": "Iron_Content",
    "cpcon_k_mean_kg_kg_dm": "Potassium_Content",
    "cpcon_n_mean_kg_kg_dm": "Nitrogen_Content",
    "cpcon_p_mean_kg_kg_dm": "Phosphorus_Content",
    "cpcon_zn_mean_kg_kg_dm": "Zinc_Content",
    "cpprot_mean_kg_kg_dm": "Protein",
    "cpy_lsd_kg_fresh_ha": "Yield_per_Hectare",
    "cpy_mean_kg_dm_ha": "Biomass_Yield",
    "cpy_mean_kg_fresh_ha": "Yield_per_Hectare",
    "cpy_sd_kg_fresh_ha": "Yield_per_Hectare",
    "cpy_se_kg_fresh_ha": "Yield_per_Hectare",
    "crop": "Crop",
    "crop types": "Crop",
    "crop_original": "Crop",
    "crop_standardised": "Crop",
    "crop_type": "Crop",
    "crude_fat": "Fat",
    "crude_fiber": "Fiber",
    "crude_protein": "Protein",
    "cry_mean_kg_fresh_ha": "Yield_per_Hectare",
    "cu": "Copper",
    "cu_ppm": "Copper",
    "cu_uptake": "Copper_Uptake",
    "cultivar": "Variety",
    "cultivation_method_name": "Cultivation_Method",
    "days_to_maturity": "Growth_Duration_Days",
    "dehydrogenase": "Dehydrogenase",
    "description_treatment_description": "Treatment",
    "design": "Design",
    "dmp_30d": "Dry_Matter",
    "dmp_60d": "Dry_Matter",
    "dmp_90d": "Dry_Matter",
    "doi": "DOI",
    "dose": "Dose",
    "dose_kg_acre": "Dose",
    "dose_kg_ha": "Dose",
    "dry_matter": "Dry_Matter",
    "dry_matter_%": "Dry_Matter",
    "dry_matter_pct": "Dry_Matter",
    "ec": "EC",
    "ec_ds_m": "EC",
    "ei": "Nematode_Enrichment_Index",
    "electrical_conductivity": "EC",
    "elevation": "Altitude",
    "enhanced_vegetation_index": "EVI",
    "et0": "ET0",
    "evi": "EVI",
    "exp_design": "Design",
    "expected_biomass": "Expected_Biomass",
    "expected_plant_height": "Expected_Plant_Height",
    "expected_yield_increase": "Expected_Yield_Increase",
    "experiment_objective_description": "Experiment_Objective",
    "experimental_design": "Design",
    "experimental_design_description": "Design",
    "experimental_objective_description": "Experiment_Objective",
    "fat": "Fat",
    "fe": "Iron",
    "fe_uptake": "Iron_Uptake",
    "fertiliser": "Fertilizer_Name",
    "fertiliser_b_kg_b_ha": "Fertilizer_Boron",
    "fertiliser_ca_kg_ca_ha": "Fertilizer_Calcium",
    "fertiliser_cl_kg_cl_ha": "Fertilizer_Chlorine",
    "fertiliser_fe_kg_fe_ha": "Iron",
    "fertiliser_k_kg_k_ha": "Potassium",
    "fertiliser_mg_kg_mg_ha": "Fertilizer_Magnesium",
    "fertiliser_mo_kg_mo_ha": "Fertilizer_Molybdenum",
    "fertiliser_n_kg_n_ha": "Nitrogen",
    "fertiliser_p_kg_p_ha": "Phosphorus",
    "fertiliser_s_kg_s_ha": "Sulphur",
    "fertiliser_type_name": "Fertilizer_Name",
    "fertiliser_zn_kg_zn_ha": "Zinc",
    "fertilizer": "Fertilizer_Name",
    "fertilizer_name": "Fertilizer_Name",
    "fiber": "Fiber",
    "first_author_name": "Authors",
    "flowers": "Flowers",
    "flowers_60": "Flowers_60",
    "flowers_plant": "Flowers",
    "fresh_weight": "Yield_per_Plot",
    "fresh_weight_g": "Yield_per_Plot",
    "fruit_diameter": "Fruit_Diameter_mm",
    "fruit_diameter_mm": "Fruit_Diameter_mm",
    "fruit_number": "Fruit_Number",
    "fruit_weight": "Fruit_Weight",
    "fruit_weight_g": "Fruit_Weight",
    "fruitdiameter_120_mm": "FruitDiameter_120_mm",
    "fruitdiameter_90_mm": "FruitDiameter_90_mm",
    "fruits_plant": "Fruit_Number",
    "fruitweight_120_g": "FruitWeight_120_g",
    "fruitweight_90_g": "FruitWeight_90_g",
    "fungal_chao1": "Fungal_Diversity_Chao1",
    "fungal_plfas": "Fungal_PLFAs",
    "fungal_shannon": "Fungal_Diversity_Shannon",
    "glucosidase": "Soil_Glucosidase",
    "gluten": "Gluten",
    "gps_coordinates_altitude": "Altitude",
    "gps_lat_dd": "Latitude",
    "gps_long_dd": "Longitude",
    "grain_iron": "Iron_Content",
    "grain_moisture": "Moisture_Content",
    "grain_nitrogen": "Nitrogen_Content",
    "grain_phosphorus": "Phosphorus_Content",
    "grain_potassium": "Potassium_Content",
    "grain_protein": "Protein",
    "grain_starch": "Starch",
    "grain_zinc": "Zinc_Content",
    "grains_per_spike": "Seeds_per_Spike",
    "gram_negative_plfas": "Gram_Negative_PLFAs",
    "gram_positive_plfas": "Gram_Positive_PLFAs",
    "growing_season": "Season",
    "growth_duration": "Growth_Duration_Days",
    "growth_duration_days": "Growth_Duration_Days",
    "growth_stage": "Growth_Stage",
    "harvest_das": "Growth_Duration_Days",
    "harvest_date": "Harvest_Date",
    "harvest_days": "Growth_Duration_Days",
    "harvest_density_plants_m2": "Harvest_Density",
    "harvest_index": "Harvest_Index",
    "harvest_stage": "Growth_Duration_Days",
    "hi_mean_unitless": "Harvest_Index",
    "humidity": "Humidity",
    "hundred_seed_weight": "100_Seed_Weight",
    "hydrogen_saturation_%": "Hydrogen_Saturation",
    "infiltration_rate": "Infiltration_Rate",
    "institution": "Institution",
    "intercrop_name": "Intercrop_Name",
    "iron": "Iron",
    "iron_content": "Iron_Content",
    "iron_mgkg": "Iron",
    "iron_ppm": "Iron",
    "iron_uptake": "Iron_Uptake",
    "irrigation": "Irrigation_Method",
    "irrigation_method_name": "Irrigation_Method",
    "journal": "Journal",
    "journal_title": "Journal",
    "k": "Potassium",
    "k2o": "Potassium",
    "k2o_kg_ha": "Potassium",
    "k_uptake": "Potassium_Uptake",
    "k_uptake_kg_ha": "Potassium_Uptake",
    "la120": "Leaf_Area_120_cm2",
    "la30": "Leaf_Area_30_cm2",
    "la60": "Leaf_Area_60_cm2",
    "la90": "Leaf_Area_90_cm2",
    "lap": "Leucine_Aminopeptidase",
    "lat": "Latitude",
    "latin_name": "Scientific_Name",
    "latitude": "Latitude",
    "leaf_area": "Leaf_Area_cm2",
    "leaf_area_120_cm2": "Leaf_Area_120_cm2",
    "leaf_area_30_cm2": "Leaf_Area_30_cm2",
    "leaf_area_60_cm2": "Leaf_Area_60_cm2",
    "leaf_area_90_cm2": "Leaf_Area_90_cm2",
    "leaf_area_cm2": "Leaf_Area_cm2",
    "leaf_number": "Leaf_Number",
    "leafarea": "Leaf_Area_cm2",
    "leaves_plant": "Leaf_Number",
    "leucine_aminopeptidase": "Leucine_Aminopeptidase",
    "location": "Location",
    "lon": "Longitude",
    "long": "Longitude",
    "longitude": "Longitude",
    "magnesium": "Magnesium",
    "magnesium_content": "Magnesium_Content",
    "magnesium_saturation_%": "Magnesium_Saturation",
    "magnesium_uptake": "Magnesium_Uptake",
    "manganese": "Manganese",
    "manganese_content": "Manganese_Content",
    "manganese_uptake": "Manganese_Uptake",
    "marketable_yield": "Marketable_Yield",
    "max_temperature": "Temperature_Max",
    "mg": "Magnesium",
    "mg_uptake": "Magnesium_Uptake",
    "mi": "Nematode_Maturity_Index",
    "min_temperature": "Temperature_Min",
    "mn": "Manganese",
    "mn_ppm": "Manganese",
    "mn_uptake": "Manganese_Uptake",
    "mo": "Molybdenum",
    "mo_uptake": "Molybdenum_Uptake",
    "moisture": "Moisture_Content",
    "moisture_content": "Moisture_Content",
    "molybdenum": "Molybdenum",
    "molybdenum_content": "Molybdenum_Content",
    "molybdenum_uptake": "Molybdenum_Uptake",
    "n": "Nitrogen",
    "n-acetyl-glucosaminidase": "N_Acetyl_Glucosaminidase",
    "n_fixation_kg_n_ha": "N_Fixation",
    "n_uptake": "Nitrogen_Uptake",
    "n_uptake_kg_ha": "Nitrogen_Uptake",
    "nag": "N_Acetyl_Glucosaminidase",
    "ndre": "NDRE",
    "ndvi": "NDVI",
    "ndvi_green": "NDVI",
    "ndwi": "NDWI",
    "nearest_town_city": "Site",
    "nematode_total_biomass_mg": "Nematode_Total_Biomass_mg",
    "net_profit": "Net_Profit",
    "nitrogen": "Nitrogen",
    "nitrogen_content": "Nitrogen_Content",
    "nitrogen_free_extract": "Carbohydrates",
    "nitrogen_kg_ha": "Nitrogen",
    "nitrogen_uptake": "Nitrogen_Uptake",
    "no_leaves": "Leaf_Number",
    "no_tillers": "Tillers",
    "nodes": "Nodes",
    "nodulation": "Nodes",
    "nue": "Nitrogen_Use_Efficiency",
    "number_of_leaves": "Leaf_Number",
    "number_of_tillers": "Tillers",
    "off-season contribution to system benefit (%)": "Off_Season_Contribution_Pct",
    "offseason": "Season",
    "oil": "Oil",
    "organic_c": "Organic_Carbon",
    "organic_carbon": "Organic_Carbon",
    "organic_carbon_%": "Organic_Carbon",
    "organic_fertilizer": "Organic_Fertilizer",
    "organic_matter": "Organic_Matter",
    "organic_matter_%": "Organic_Matter",
    "organiccarbon": "Organic_Carbon",
    "organicmatter": "Organic_Matter",
    "p": "Phosphorus",
    "p2o5": "Phosphorus",
    "p2o5_kg_ha": "Phosphorus",
    "p_uptake": "Phosphorus_Uptake",
    "p_uptake_kg_ha": "Phosphorus_Uptake",
    "panicle_length": "Spike_Length",
    "paper_id": "Paper_ID",
    "pe": "Potential_Evapotranspiration",
    "peroxidase": "Peroxidase",
    "ph": "Soil_pH",
    "ph120": "Plant_Height_120_cm",
    "ph30": "Plant_Height_30_cm",
    "ph60": "Plant_Height_60_cm",
    "ph90": "Plant_Height_90_cm",
    "phenological_stage": "Growth_Stage",
    "phosphatase": "Phosphatase",
    "phosphorus": "Phosphorus",
    "phosphorus_content": "Phosphorus_Content",
    "phosphorus_uptake": "Phosphorus_Uptake",
    "plant_height": "Plant_Height_cm",
    "plant_height_120_cm": "Plant_Height_120_cm",
    "plant_height_30_cm": "Plant_Height_30_cm",
    "plant_height_60_cm": "Plant_Height_60_cm",
    "plant_height_90_cm": "Plant_Height_90_cm",
    "plant_height_cm": "Plant_Height_cm",
    "plant_spacing": "Spacing_Plant",
    "plant_spacing_cm": "Spacing_Plant",
    "plantheight": "Plant_Height_cm",
    "plot_area": "Plot_Size",
    "plot_id": "Plot_ID",
    "plot_size": "Plot_Size",
    "plot_size_m2": "Plot_Size",
    "pod_weight": "Pod_Weight",
    "pod_weight_g": "Pod_Weight",
    "pods_number": "Pods_Number",
    "polyphenol_oxidase": "Polyphenol_Oxidase",
    "potassium": "Potassium",
    "potassium_content": "Potassium_Content",
    "potassium_saturation_%": "Potassium_Saturation",
    "potassium_uptake": "Potassium_Uptake",
    "ppi": "Nematode_Plant_Parasitic_Index",
    "ppo": "Polyphenol_Oxidase",
    "precipitation": "Rainfall",
    "predicted_yield": "Predicted_Yield",
    "previous_crop_name": "Previous_Crop",
    "protein": "Protein",
    "protein_%": "Protein",
    "protein_content": "Protein",
    "pue": "Water_Use_Efficiency",
    "rainfall": "Rainfall",
    "rainfall_mm": "Rainfall",
    "recommendation_summary": "Recommendation_Summary",
    "recommended_application_interval": "Recommended_Application_Interval",
    "recommended_dose": "Recommended_Dose",
    "recommended_fertilizer": "Recommended_Fertilizer",
    "relative_humidity": "Humidity",
    "rep": "Replications",
    "replicate": "Replications",
    "replicate_n": "Replications",
    "replicate_num": "Replications",
    "replicates": "Replications",
    "replications": "Replications",
    "residue/root c decomposition": "Residue_C_Decomposition",
    "residue_c_decomposition": "Residue_C_Decomposition",
    "root_biomass": "Root_Biomass_g",
    "root_biomass_ash_free": "Root_Biomass_g",
    "root_biomass_g": "Root_Biomass_g",
    "root_diameter": "Root_Diameter_mm",
    "root_diameter_mm": "Root_Diameter_mm",
    "root_length": "Root_Length_cm",
    "root_length_cm": "Root_Length_cm",
    "root_shoot_ratio": "Root_Length_cm",
    "root_volume": "Root_Diameter_mm",
    "root_weight": "Root_Weight",
    "root_weight_g": "Root_Weight",
    "rooting_depth": "Root_Length_cm",
    "row_spacing": "Spacing_Row",
    "row_spacing_cm": "Spacing_Row",
    "rwc": "Moisture_Content",
    "s": "Sulphur",
    "s_uptake": "Sulphur_Uptake",
    "sample date": "Season",
    "sample_size": "Sample_Size",
    "savi": "SAVI",
    "scientific_name": "Scientific_Name",
    "scientificname": "Scientific_Name",
    "season": "Season",
    "seed_yield": "Seed_Yield",
    "seeds_per_pod": "Seeds_per_Pod",
    "seeds_per_spike": "Seeds_per_Spike",
    "seeds_spike": "Seeds_per_Spike",
    "shoot_biomass": "Shoot_Biomass_g",
    "shoot_biomass_g": "Shoot_Biomass_g",
    "shoot_height": "Shoot_Length_cm",
    "shoot_length": "Shoot_Length_cm",
    "shoot_length_cm": "Shoot_Length_cm",
    "shootheight": "Shoot_Length_cm",
    "si": "Nematode_Structure_Index",
    "site": "Location",
    "soc_mineralization": "SOC_Mineralization",
    "sodium_saturation_%": "Sodium_Saturation",
    "soil depth (cm)": "Soil_Depth_cm",
    "soil ph": "Soil_pH",
    "soil_adjusted_vegetation_index": "SAVI",
    "soil_boron_mg_kg": "Boron",
    "soil_bulk_density_mg_cm3": "Soil_Bulk_Density",
    "soil_ca_(ammonium_acetate)_mg_ca_kg": "Soil_Ca_Ammonium_Acetate",
    "soil_ca_mehlich-3_mg_ca_kg": "Calcium_Mehlich3",
    "soil_carbon_(walkley-black)_%": "Soil_Carbon_Walkley_Black",
    "soil_cec_cmol_kg": "CEC",
    "soil_cl_mg_kg": "Chlorine",
    "soil_class": "Soil_Class",
    "soil_clay_%": "Soil_Clay_Pct",
    "soil_cu_detpa_extractable_mg_kg": "Copper",
    "soil_depth_cm": "Soil_Depth_cm",
    "soil_fe_detpa_extractable_mg_kg": "Iron",
    "soil_k_(ammonium_acetate)_mg_k_kg": "Soil_K_Ammonium_Acetate",
    "soil_k_(black)_kg_k_ha": "Potassium",
    "soil_k_(mehlich-3)_mg_k_kg": "Potassium",
    "soil_k_dry_mg_k_kg": "Potassium",
    "soil_k_exchangeable_mg_k_kg": "Potassium",
    "soil_k_wet_mg_k_kg": "Potassium",
    "soil_mbc_mg_c_kg": "Soil_MBC",
    "soil_mbn_mg_n_kg": "Soil_MBN",
    "soil_mg_(ammonium_acetate)_mg_k_kg": "Soil_Mg_Ammonium_Acetate",
    "soil_mn_detpa_extractable_mg_kg": "Manganese",
    "soil_moisture_%": "Soil_Moisture",
    "soil_moisture_%_whc": "Soil_Moisture",
    "soil_molybdenum_mg_kg": "Molybdenum",
    "soil_n_(de silva 2008)_kg_n_ha": "Soil_N_DeSilva2008",
    "soil_n_(parco2020)_kg_n_ha": "Soil_N_Parco2020",
    "soil_n_alkaline_permanganate_kg_n_ha": "Soil_Nitrogen_Alkaline_Permanganate",
    "soil_na_mg_kg": "Sodium",
    "soil_nc_kjeldahl_g_n_kg": "Soil_Nitrogen_Kjeldahl",
    "soil_nh4": "Soil_NH4",
    "soil_nitrate": "Soil_NO3",
    "soil_om_%": "Organic_Matter",
    "soil_p_bray_1_mg_p_kg": "Phosphorus",
    "soil_p_bray_2_mg_p_kg": "Phosphorus",
    "soil_p_mehlich-3_mg_p_kg": "Phosphorus",
    "soil_p_olsen_mg_kg": "Phosphorus",
    "soil_ph": "Soil_pH",
    "soil_ph_cacl2": "Soil_pH_CaCl2",
    "soil_ph_cacl2_number": "Soil_pH_CaCl2",
    "soil_ph_h2o_1:1_number": "Soil_pH",
    "soil_ph_h2o_1:2.5_number": "Soil_pH",
    "soil_ph_kcl": "Soil_pH_KCl",
    "soil_ph_kcl_number": "Soil_pH_KCl",
    "soil_respiration": "Soil_Respiration",
    "soil_s_(cacl2)_mg_s_kg": "Soil_Sulphur_Available",
    "soil_s_(mehlich-3)_mg_s_kg": "Soil_Sulphur_Mehlich3",
    "soil_sand_%": "Soil_Sand_Pct",
    "soil_silt_%": "Soil_Silt_Pct",
    "soil_soc_k2cr2o7_g_c_kg": "Organic_Carbon",
    "soil_sodium": "Sodium",
    "soil_texture_name": "Soil_Texture",
    "soil_water_nh4_mg_n_kg": "Soil_Ammonium_N",
    "soil_water_nitrate_mg_n_kg": "Soil_Nitrate_N",
    "soil_zn_detpa_extractable_mg_kg": "Zinc",
    "solar_radiation": "Solar_Radiation",
    "sow_density_seeds_m2": "Sowing_Density",
    "sowing_date": "Sowing_Date",
    "spacing_plant": "Spacing_Plant",
    "spacing_row": "Spacing_Row",
    "spad": "SPAD",
    "spike_length": "Spike_Length",
    "spike_length_cm": "Spike_Length",
    "starch": "Starch",
    "state": "State",
    "state_province": "State",
    "stem_biomass": "Shoot_Biomass_g",
    "stem_diameter": "Stem_Diameter_mm",
    "stem_diameter_mm": "Stem_Diameter_mm",
    "stover_yield": "Stover_Yield",
    "sulfur": "Sulphur",
    "sulphur": "Sulphur",
    "sulphur_content": "Sulphur_Content",
    "sulphur_ppm": "Sulphur",
    "sulphur_uptake": "Sulphur_Uptake",
    "system benefit (usd/ha)": "System_Benefit_USD_ha",
    "system benefit cost ratio": "Benefit_Cost_Ratio",
    "system rice equivalent yield (t/ha)": "Yield_per_Hectare",
    "system water use efficiency (kg/m3/ha)": "System_Water_Use_Efficiency",
    "target_fertilizer": "Target_Fertilizer",
    "target_nitrogen": "Target_Nitrogen",
    "target_phosphorus": "Target_Phosphorus",
    "target_potassium": "Target_Potassium",
    "target_yield": "Target_Yield",
    "temp": "Average_Temperature",
    "temp_max": "Temperature_Max",
    "temp_min": "Temperature_Min",
    "temperature": "Average_Temperature",
    "temperature_max": "Temperature_Max",
    "temperature_min": "Temperature_Min",
    "test_weight": "100_Seed_Weight",
    "tiller_number": "Tillers",
    "tillers": "Tillers",
    "title_of_article": "Title",
    "tmax": "Temperature_Max",
    "tmax_c": "Temperature_Max",
    "tmin": "Temperature_Min",
    "tmin_c": "Temperature_Min",
    "total_cost": "Total_Cost",
    "total_plfas": "Total_PLFAs",
    "total_return": "Total_Return",
    "treatment": "Treatment",
    "treatment_name": "Treatment",
    "treatments": "Treatment",
    "urease": "Urease",
    "variety": "Variety",
    "water amount (mm)": "Rainfall",
    "water_amount_mm": "Irrigation_mm",
    "water_extractable_cn": "Water_Extractable_CN_Ratio",
    "water_extractable_nh4": "Water_Extractable_NH4",
    "water_extractable_nitrate": "Water_Extractable_Nitrate",
    "water_extractable_organic_carbon": "Water_Extractable_Organic_Carbon",
    "water_extractable_organic_nitrogen": "Water_Extractable_Organic_Nitrogen",
    "wec_cn_ratio": "Water_Extractable_CN_Ratio",
    "wec_n_mg_n_kg": "Water_Extractable_Nitrate",
    "wec_nh4_mg_n_kg": "Water_Extractable_NH4",
    "wec_nh4_n_mg_n_kg": "Water_Extractable_NH4",
    "wec_no3_n_mg_n_kg": "Water_Extractable_Nitrate",
    "wec_oc_mg_c_kg": "Water_Extractable_Organic_Carbon",
    "wec_oc_mg_oc_kg": "Water_Extractable_Organic_Carbon",
    "wec_on_mg_n_kg": "Water_Extractable_Organic_Nitrogen",
    "wec_on_mg_on_kg": "Water_Extractable_Organic_Nitrogen",
    "weed_biomass": "Weed_Biomass",
    "weight_100_seeds_g": "100_Seed_Weight",
    "wet yield (t/ha)": "Yield_per_Hectare",
    "wind_speed": "Wind_Speed",
    "wue": "Water_Use_Efficiency",
    "xylosidase": "Soil_Xylosidase",
    "year": "Year",
    "yield": "Yield_per_Plot",
    "yield_13%_moisture": "Yield_13pct_Moisture",
    "yield_per_acre": "Yield_per_Acre",
    "yield_per_ha": "Yield_per_Hectare",
    "yield_per_hectare": "Yield_per_Hectare",
    "yield_per_plot": "Yield_per_Plot",
    "yield_per_plot_g": "Yield_per_Plot",
    "yield_plot": "Yield_per_Plot",
    "yieldplot_120_g": "YieldPlot_120_g",
    "yieldplot_90_g": "YieldPlot_90_g",
    "zinc": "Zinc",
    "zinc_content": "Zinc_Content",
    "zinc_uptake": "Zinc_Uptake",
    "zn": "Zinc",
    "zn_ppm": "Zinc",
    "zn_uptake": "Zinc_Uptake",
}

NON_FEATURE_COLS = frozenset(
    {
        "Treatment",
        "Table_Row",
        "Row_Index",
        "_source_page",
        "_reader",
        "_confidence",
        "Source_File",
        "Paper_ID",
        "DOI",
        "Journal",
        "Authors",
        "Country",
        "Location",
        "State",
        "Site",
        "Feature_Available_Before_Prediction",
        "Crop_Code",
        "Season_Code",
        "Variety_Code",
        "Fertilizer_Code",
        "Soil_Texture_Code",
        "Country_Code",
        "Title",
        "Institution",
        "Plot_ID",
        "Block",
        "Sowing_Date",
        "Harvest_Date",
        "Fertilizer_Name",
        "Organic_Fertilizer",
        "Biofertilizer",
        "Application_Method",
        "Application_Interval",
        "Design",
        "Experiment_Objective",
        "Irrigation_Method",
        "Cultivation_Method",
        "Cover_Crop",
        "Previous_Crop",
        "Intercrop_Name",
        "Climate_Zone",
    }
)

POST_HARVEST_VARIABLES = frozenset(
    {
        "Protein",
        "Ash",
        "Gluten",
        "Fiber",
        "Carbohydrates",
        "Fat",
        "Nitrogen_Content",
        "Phosphorus_Content",
        "Potassium_Content",
        "Iron_Content",
        "Copper_Content",
        "Zinc_Content",
        "Manganese_Content",
        "Sulphur_Content",
        "Calcium_Content",
        "Magnesium_Content",
        "Boron_Content",
        "Chlorine_Content",
        "Molybdenum_Content",
        "Starch",
        "Oil",
        "100_Seed_Weight",
        "Root_Weight",
        "Pod_Weight",
        "Harvest_Index",
        "Biomass_Yield",
        "Yield_per_Plot",
        "Yield_per_Acre",
        "Yield_per_Hectare",
        "Yield_13pct_Moisture",
        "Marketable_Yield",
        "Biological_Yield",
        "Stover_Yield",
        "Seed_Yield",
        "Fruit_Number",
        "Fruit_Weight",
        "Fruit_Diameter_mm",
        "FruitWeight_90_g",
        "FruitWeight_120_g",
        "FruitDiameter_90_mm",
        "FruitDiameter_120_mm",
        "YieldPlot_90_g",
        "YieldPlot_120_g",
        "Spike_Length",
        "Seeds_per_Spike",
        "Pods_Number",
        "Seeds_per_Pod",
        "Target_Yield",
        "Target_Fertilizer",
        "Target_Nitrogen",
        "Target_Phosphorus",
        "Target_Potassium",
        "Yield_per_Plant",
        "Yield_per_Plot_Calc",
        "Yield_per_Hectare_Calc",
        "Nitrogen_Use_Efficiency",
        "Water_Use_Efficiency",
        "Harvest_Index_Calc",
        "Total_Cost",
        "Total_Return",
        "Net_Profit",
        "Benefit_Cost_Ratio",
        "System_Benefit_USD_ha",
        "Off_Season_Contribution_Pct",
    }
)

PRE_HARVEST_MEASUREMENTS = frozenset(
    {
        "Leaf_Number",
        "Tillers",
        "Branches",
        "Nodes",
        "Flowers",
        "Plant_Height_30_cm",
        "Plant_Height_60_cm",
        "Plant_Height_90_cm",
        "Plant_Height_120_cm",
        "Leaf_Area_30_cm2",
        "Leaf_Area_60_cm2",
        "Leaf_Area_90_cm2",
        "Leaf_Area_120_cm2",
        "Branches_60",
        "Branches_90",
        "Flowers_60",
        "SPAD",
        "Moisture_Content",
        "Dry_Matter",
        "Shoot_Length_cm",
        "Root_Length_cm",
        "Stem_Diameter_mm",
        "Root_Diameter_mm",
        "Plant_Height_cm",
        "Shoot_Biomass_g",
        "Root_Biomass_g",
        # Soil biological / enzyme / microbial
        "SOC_Mineralization",
        "Residue_C_Decomposition",
        "Soil_Moisture",
        "Soil_MBC",
        "Soil_MBN",
        "Soil_Glucosidase",
        "Soil_Xylosidase",
        "Soil_Cellobiosidase",
        "Beta_Glucosidase",
        "Peroxidase",
        "Polyphenol_Oxidase",
        "N_Acetyl_Glucosaminidase",
        "Leucine_Aminopeptidase",
        "Phosphatase",
        "Catalase",
        "Urease",
        "Dehydrogenase",
        "Bacterial_Diversity_Chao1",
        "Bacterial_Diversity_Shannon",
        "Fungal_Diversity_Chao1",
        "Fungal_Diversity_Shannon",
        "Total_PLFAs",
        "Gram_Positive_PLFAs",
        "Gram_Negative_PLFAs",
        "Fungal_PLFAs",
        "Bacterial_PLFAs",
        "Actinomycetes_PLFAs",
        # Remote sensing
        "NDVI",
        "EVI",
        "SAVI",
        "NDWI",
        "NDRE",
        "Canopy_Temperature",
        "CIG",
        "CIRE",
        # Soil physical
        "Aggregate_Stability",
        "Soil_Respiration",
        "Infiltration_Rate",
        # Nematode
        "Nematode_Maturity_Index",
        "Nematode_Plant_Parasitic_Index",
        "Nematode_Channel_Index",
        "Nematode_Basal_Index",
        "Nematode_Enrichment_Index",
        "Nematode_Structure_Index",
        # Nutrient uptake
        "Nitrogen_Uptake",
        "Phosphorus_Uptake",
        "Potassium_Uptake",
    }
)

NUMERIC_UAMS_COLUMNS = frozenset(
    {
        # B
        "Growth_Duration_Days",
        # C
        "Replications",
        # D
        "Latitude",
        "Longitude",
        "Altitude",
        "Temperature_Max",
        "Temperature_Min",
        "Average_Temperature",
        "Rainfall",
        "Humidity",
        "Solar_Radiation",
        "Wind_Speed",
        "ET0",
        # E
        "Soil_pH",
        "EC",
        "Organic_Carbon",
        "Organic_Matter",
        "Nitrogen",
        "Phosphorus",
        "Potassium",
        "Sulphur",
        "Iron",
        "Copper",
        "Manganese",
        "Zinc",
        "Calcium",
        "Magnesium",
        "Boron",
        "Molybdenum",
        "Sodium",
        "Chlorine",
        "CEC",
        "Soil_Bulk_Density",
        "Soil_Clay_Pct",
        "Soil_Silt_Pct",
        "Soil_Sand_Pct",
        "Soil_Depth_cm",
        # F
        "Dose",
        # G
        "Shoot_Length_cm",
        "Root_Length_cm",
        "Plant_Height_cm",
        "Shoot_Biomass_g",
        "Root_Biomass_g",
        "Leaf_Area_cm2",
        "Leaf_Number",
        "Tillers",
        "Root_Diameter_mm",
        "SPAD",
        "Moisture_Content",
        "Dry_Matter",
        "Stem_Diameter_mm",
        "Branches",
        "Nodes",
        "Flowers",
        "Plant_Height_30_cm",
        "Plant_Height_60_cm",
        "Plant_Height_90_cm",
        "Plant_Height_120_cm",
        "Leaf_Area_30_cm2",
        "Leaf_Area_60_cm2",
        "Leaf_Area_90_cm2",
        "Leaf_Area_120_cm2",
        "Branches_60",
        "Branches_90",
        "Flowers_60",
        # H
        "Yield_per_Plot",
        "Yield_per_Acre",
        "Yield_per_Hectare",
        "Fruit_Number",
        "Fruit_Weight",
        "Fruit_Diameter_mm",
        "Spike_Length",
        "Seeds_per_Spike",
        "100_Seed_Weight",
        "Root_Weight",
        "Pod_Weight",
        "Harvest_Index",
        "Biomass_Yield",
        "FruitWeight_90_g",
        "FruitWeight_120_g",
        "FruitDiameter_90_mm",
        "FruitDiameter_120_mm",
        "YieldPlot_90_g",
        "YieldPlot_120_g",
        "Yield_13pct_Moisture",
        "Marketable_Yield",
        "Biological_Yield",
        "Stover_Yield",
        "Seed_Yield",
        "Pods_Number",
        "Seeds_per_Pod",
        "Weed_Biomass",
        # I
        "Protein",
        "Ash",
        "Gluten",
        "Fiber",
        "Carbohydrates",
        "Fat",
        "Nitrogen_Content",
        "Phosphorus_Content",
        "Potassium_Content",
        "Iron_Content",
        "Copper_Content",
        "Zinc_Content",
        "Manganese_Content",
        "Sulphur_Content",
        "Calcium_Content",
        "Magnesium_Content",
        "Boron_Content",
        "Chlorine_Content",
        "Molybdenum_Content",
        "Starch",
        "Oil",
        # J
        "Target_Yield",
        "Target_Nitrogen",
        "Target_Phosphorus",
        "Target_Potassium",
        # K
        "Growing_Degree_Days",
        "Heat_Units",
        "Harvest_Index_Calc",
        "Nitrogen_Use_Efficiency",
        "Water_Use_Efficiency",
        "Rainfall_Anomaly",
        "Stress_Index",
        "Disease_Risk_Index",
        "Yield_per_Plant",
        "Yield_per_Plot_Calc",
        "Yield_per_Hectare_Calc",
        "Temp_x_Rainfall",
        "N_x_P",
        "Temp_squared",
        "Rainfall_7d_MA",
        "Temp_7d_MA",
        # N
        "Expected_Yield_Increase",
        "Confidence_Score",
        # O
        "SOC_Mineralization",
        "Residue_C_Decomposition",
        "Potential_Evapotranspiration",
        "Soil_Moisture",
        "Soil_Nitrate_N",
        "Soil_Ammonium_N",
        "Soil_Available_K",
        "Soil_NO3",
        "Soil_NH4",
        "Soil_MBC",
        "Soil_MBN",
        "Soil_Carbon_Walkley_Black",
        "Soil_Nitrogen_Kjeldahl",
        "Soil_Nitrogen_Alkaline_Permanganate",
        "Soil_Sulphur_Available",
        "Soil_Sulphur_Mehlich3",
        "Soil_N_Parco2020",
        "Soil_N_DeSilva2008",
        "Soil_Ca_Ammonium_Acetate",
        "Soil_Mg_Ammonium_Acetate",
        "Soil_K_Ammonium_Acetate",
        "Soil_pH_CaCl2",
        "Soil_pH_KCl",
        # P
        "Soil_Glucosidase",
        "Soil_Xylosidase",
        "Soil_Cellobiosidase",
        "Beta_Glucosidase",
        "Peroxidase",
        "Polyphenol_Oxidase",
        "N_Acetyl_Glucosaminidase",
        "Leucine_Aminopeptidase",
        "Phosphatase",
        "Catalase",
        "Urease",
        "Dehydrogenase",
        # Q
        "Bacterial_Diversity_Chao1",
        "Bacterial_Diversity_Shannon",
        "Fungal_Diversity_Chao1",
        "Fungal_Diversity_Shannon",
        "Total_PLFAs",
        "Gram_Positive_PLFAs",
        "Gram_Negative_PLFAs",
        "Fungal_PLFAs",
        "Bacterial_PLFAs",
        "Actinomycetes_PLFAs",
        # R
        "NDVI",
        "EVI",
        "SAVI",
        "NDWI",
        "NDRE",
        "Canopy_Temperature",
        "CIG",
        "CIRE",
        # S
        "Calcium_Mehlich3",
        "Calcium_Saturation",
        "Magnesium_Saturation",
        "Sodium_Saturation",
        "Potassium_Saturation",
        "Hydrogen_Saturation",
        # T
        "Water_Extractable_Nitrate",
        "Water_Extractable_Organic_Carbon",
        "Water_Extractable_Organic_Nitrogen",
        "Water_Extractable_NH4",
        "Water_Extractable_CN_Ratio",
        # U
        "Aggregate_Stability",
        "Soil_Respiration",
        "Infiltration_Rate",
        # V
        "Nematode_Maturity_Index",
        "Nematode_Plant_Parasitic_Index",
        "Nematode_Channel_Index",
        "Nematode_Basal_Index",
        "Nematode_Enrichment_Index",
        "Nematode_Structure_Index",
        "Nematode_Total_Biomass_mg",
        # W
        "Total_Cost",
        "Total_Return",
        "Net_Profit",
        "Benefit_Cost_Ratio",
        "System_Benefit_USD_ha",
        "Off_Season_Contribution_Pct",
        "System_Water_Use_Efficiency",
        # X
        "Phosphorus_Uptake",
        "Nitrogen_Uptake",
        "Potassium_Uptake",
        "Sulphur_Uptake",
        "Calcium_Uptake",
        "Magnesium_Uptake",
        "Boron_Uptake",
        "Chlorine_Uptake",
        "Copper_Uptake",
        "Iron_Uptake",
        "Manganese_Uptake",
        "Molybdenum_Uptake",
        "Zinc_Uptake",
        # Y
        "Irrigation_mm",
        "Sowing_Density",
        "Harvest_Density",
    }
)

CATEGORICAL_UAMS_COLUMNS = frozenset(
    {
        # A
        "Title",
        "DOI",
        "Journal",
        "Authors",
        "Country",
        "Institution",
        # B
        "Crop",
        "Scientific_Name",
        "Variety",
        "Season",
        "Growth_Stage",
        "Cover_Crop",
        "Previous_Crop",
        "Intercrop_Name",
        # C
        "Design",
        "Plot_Size",
        "Sample_Size",
        "Location",
        "State",
        "Site",
        "Plot_ID",
        "Block",
        "Experiment_Objective",
        "Sowing_Date",
        "Harvest_Date",
        # D
        "Climate_Zone",
        # E
        "Soil_Texture",
        "Soil_Class",
        # F
        "Treatment",
        "Fertilizer_Name",
        "Organic_Fertilizer",
        "Biofertilizer",
        "Application_Method",
        "Application_Interval",
        # J
        "Target_Fertilizer",
        # N
        "Recommended_Fertilizer",
        "Recommended_Application_Interval",
        "Recommendation_Summary",
        # Y
        "Irrigation_Method",
        "Cultivation_Method",
    }
)

# Measured agronomic outcomes to model when no synthetic Target_* column is populated,
# in order of preference. Mirrors the columns the validated monolith actually trained on.
MEASURED_TARGETS = [
    "Yield_per_Hectare",
    "Yield_per_Plot",
    "Plant_Height_cm",
    "SPAD",
    "Shoot_Biomass_g",
]

MIN_TARGET_ROWS = 5


def resolve_target_column(df, requested=None, extra_targets=None, min_non_null=MIN_TARGET_ROWS):
    """Return a usable target column name, or None.

    Prefers the requested column, then any synthetic Target_* passed as extra_targets,
    then the measured agronomic outcomes; a candidate is accepted only if it exists and
    has at least ``min_non_null`` non-null values.
    """
    candidates = []
    if requested:
        candidates.append(requested)
    if extra_targets:
        candidates.extend(extra_targets)
    candidates.extend(MEASURED_TARGETS)
    seen = set()
    for col in candidates:
        if col in seen:
            continue
        seen.add(col)
        if col in df.columns and df[col].notna().sum() >= min_non_null:
            return col
    return None
